/*********************************************************************
*                SEGGER MICROCONTROLLER SYSTEME GmbH                 *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*
* C-file generated by
*
*        µC/GUI-BitmapConvert V3.96.
*        Compiled Jul 19 2005, 13:50:35
*          (c) 2002-2005  Micrium, Inc.
  www.micrium.com

  (c) 1998-2005  Segger
  Microcontroller Systeme GmbH
  www.segger.com
*
**********************************************************************
*
* Source file: Mark_HLeftIcon
* Dimensions:  8 * 9
* NumColors:   0
*
**********************************************************************
*/

#include "stdlib.h"

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif


static GUI_CONST_STORAGE unsigned char acMark_HLeftIcon[] = {
  /* RLE: 003 Pixels @ 000,000*/ 3, 0x00, 0x00, 
  /* RLE: 001 Pixels @ 003,000*/ 1, 0xE0, 0xFF, 
  /* RLE: 007 Pixels @ 004,000*/ 7, 0x00, 0x00, 
  /* ABS: 002 Pixels @ 003,001*/ 0, 2, 0xE0, 0xFF, 0xE0, 0xFF, 
  /* RLE: 006 Pixels @ 005,001*/ 6, 0x00, 0x00, 
  /* RLE: 003 Pixels @ 003,002*/ 3, 0xE0, 0xFF, 
  /* RLE: 005 Pixels @ 006,002*/ 5, 0x00, 0x00, 
  /* RLE: 004 Pixels @ 003,003*/ 4, 0xE0, 0xFF, 
  /* RLE: 001 Pixels @ 007,003*/ 1, 0x00, 0x00, 
  /* RLE: 008 Pixels @ 000,004*/ 8, 0xE0, 0xFF, 
  /* RLE: 003 Pixels @ 000,005*/ 3, 0x00, 0x00, 
  /* RLE: 004 Pixels @ 003,005*/ 4, 0xE0, 0xFF, 
  /* RLE: 004 Pixels @ 007,005*/ 4, 0x00, 0x00, 
  /* RLE: 003 Pixels @ 003,006*/ 3, 0xE0, 0xFF, 
  /* RLE: 005 Pixels @ 006,006*/ 5, 0x00, 0x00, 
  /* ABS: 002 Pixels @ 003,007*/ 0, 2, 0xE0, 0xFF, 0xE0, 0xFF, 
  /* RLE: 006 Pixels @ 005,007*/ 6, 0x00, 0x00, 
  /* RLE: 001 Pixels @ 003,008*/ 1, 0xE0, 0xFF, 
  /* RLE: 004 Pixels @ 004,008*/ 4, 0x00, 0x00, 


  0};  /* 42 for 72 pixels */

GUI_CONST_STORAGE GUI_BITMAP bmMark_HLeftIcon = {
  8, /* XSize */
  9, /* YSize */
  16, /* BytesPerLine */
  16, /* BitsPerPixel */
  (unsigned char *)acMark_HLeftIcon,  /* Pointer to picture data */
  NULL  /* Pointer to palette */
 ,GUI_DRAW_RLEM16
};

/* *** End of file *** */
