/*********************************************************************
*                SEGGER MICROCONTROLLER SYSTEME GmbH                 *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*
* C-file generated by
*
*        µC/GUI-BitmapConvert V3.96.
*        Compiled Jul 19 2005, 13:50:35
*          (c) 2002-2005  Micrium, Inc.
  www.micrium.com

  (c) 1998-2005  Segger
  Microcontroller Systeme GmbH
  www.segger.com
*
**********************************************************************
*
* Source file: Mark_VDownIcon
* Dimensions:  9 * 8
* NumColors:   0
*
**********************************************************************
*/

#include "stdlib.h"

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif


static GUI_CONST_STORAGE unsigned char acMark_VDownIcon[] = {
  /* RLE: 004 Pixels @ 000,000*/ 4, 0x00, 0x00, 
  /* RLE: 001 Pixels @ 004,000*/ 1, 0xE0, 0xFF, 
  /* RLE: 008 Pixels @ 005,000*/ 8, 0x00, 0x00, 
  /* RLE: 001 Pixels @ 004,001*/ 1, 0xE0, 0xFF, 
  /* RLE: 008 Pixels @ 005,001*/ 8, 0x00, 0x00, 
  /* RLE: 001 Pixels @ 004,002*/ 1, 0xE0, 0xFF, 
  /* RLE: 004 Pixels @ 005,002*/ 4, 0x00, 0x00, 
  /* RLE: 009 Pixels @ 000,003*/ 9, 0xE0, 0xFF, 
  /* RLE: 001 Pixels @ 000,004*/ 1, 0x00, 0x00, 
  /* RLE: 007 Pixels @ 001,004*/ 7, 0xE0, 0xFF, 
  /* RLE: 003 Pixels @ 008,004*/ 3, 0x00, 0x00, 
  /* RLE: 005 Pixels @ 002,005*/ 5, 0xE0, 0xFF, 
  /* RLE: 005 Pixels @ 007,005*/ 5, 0x00, 0x00, 
  /* RLE: 003 Pixels @ 003,006*/ 3, 0xE0, 0xFF, 
  /* RLE: 007 Pixels @ 006,006*/ 7, 0x00, 0x00, 
  /* RLE: 001 Pixels @ 004,007*/ 1, 0xE0, 0xFF, 
  /* RLE: 004 Pixels @ 005,007*/ 4, 0x00, 0x00, 


  0};  /* 34 for 72 pixels */

GUI_CONST_STORAGE GUI_BITMAP bmMark_VDownIcon = {
  9, /* XSize */
  8, /* YSize */
  18, /* BytesPerLine */
  16, /* BitsPerPixel */
  (unsigned char *)acMark_VDownIcon,  /* Pointer to picture data */
  NULL  /* Pointer to palette */
 ,GUI_DRAW_RLEM16
};

/* *** End of file *** */
